# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            R Programming for Biologists
description:      'Teaching the tools to get computers to do cool science'
url:              http://rsh249.github.io/semester-biology
baseurl:          https://rsh249.github.io/semester-biology
email:            rharbert@stonehill.edu

author:
  name:           'Dr. Robert Harbert'
  url:            https://rsh249.github.io

github:
  repo:           https://github.com/rsh249/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
